services:
  - type: web
    name: mentora-node-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: JWT_SECRET
        value: your-secret
      - key: APPLE_CLIENT_ID
        value: ...
      - key: APPLE_TEAM_ID
        value: ...
      - key: APPLE_KEY_ID
        value: ...
